[package]
name = "pg_later"
version = "0.0.4"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg_test = []

[dependencies]
pgmq = "0.13.0"
pgrx = "=0.9.8"
serde = "1.0.164"
serde_json = "1.0.99"

[dev-dependencies]
pgrx-tests = "=0.9.8"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
