[extension]
name = "pg_later"
repository = "https://github.com/tembo-io/pg_later"
license = "PostgreSQL"
description = "Execute SQL statements now and check the results later."
homepage = "https://github.com/tembo-io/pg_later"
documentation = "https://github.com/tembo-io/pg_later"
categories = ["orchestration"]
version = "0.1.1"

[build]
postgres_version = "15"
platform = "linux/amd64"
